### PR TITLE
Extract missing CodeMeta terms from GitHub API

### PR DESCRIPTION
**Pull request by cmdoret**
This PR adds support for terms defined in [CodeMeta's Github Crosswalk](https://github.com/codemeta/codemeta/blob/master/crosswalks/GitHub.csv) and more:

CodeMeta term | Concept | Property | Github field | type
--|--|--|--|--
:white_check_mark: | SoftwareSourceCode | name | name | text
:white_check_mark: | SoftwareSourceCode | author | owner | Person
:white_check_mark: | SoftwareSourceCode | contributor | contributors | Person
:white_check_mark: | SoftwareSourceCode | programmingLanguage | languages_url | text
:white_check_mark: | SoftwareSourceCode | dateCreated | name | datetime
:white_check_mark: | SoftwareSourceCode | dateModified | name | datetime
:white_check_mark: | SoftwareSourceCode | downloadUrl | archive_url | URL
:white_check_mark: | SoftwareSourceCode | license | license | URL
:white_check_mark: | SoftwareSourceCode | codeRepository | html_repository | URL
:white_check_mark: | SoftwareSourceCode | keywords | topics | text
:white_check_mark: | SoftwareSourceCode |  version | release_name | text
:white_check_mark: | Organization | name | login | text
:white_check_mark: | Organization | email | email | text
:white_check_mark: | Person | name | name | text
:white_check_mark: | Person | identifier | login | text
:x: | Organization | logo | avatar_url | URL
:x: | Organization | legalName | name | text

> Note: The new Organization properties (logo and legalName) are only gathered for the Organization that "owns" the project, not for users' affiliations. This could be added, but would significantly slow down the process since it requires an additional query for each affiliation of each user.

Example output:

```ttl
@prefix schema: <http://schema.org/> .

<https://api.github.com/orgs/SwissDataScienceCenter> a schema:Organization ;
    schema:description "An ETH Domain initiative for accelerating the adoption of data science" ;
    schema:name "SwissDataScienceCenter" .

<https://api.github.com/orgs/koszullab> a schema:Organization ;
    schema:description "" ;
    schema:name "koszullab" .

<https://api.github.com/users/cmdoret> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD>,
        <https://api.github.com/orgs/SwissDataScienceCenter>,
        <https://api.github.com/orgs/koszullab> ;
    schema:identifier "cmdoret" ;
    schema:name "Cyril Matthey-Doret" .

<https://api.github.com/users/martinfontanet> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD> ;
    schema:identifier "martinfontanet" .

<https://api.github.com/users/rmfranken> a schema:Person ;
    schema:identifier "rmfranken" .

<https://api.github.com/users/sabinem> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD> ;
    schema:identifier "sabinem" ;
    schema:name "Sabine Maennel" .

<https://api.github.com/users/sabrinaossey> a schema:Person ;
    schema:identifier "sabrinaossey" ;
    schema:name "sabrinaossey" .

<https://github.com/SDSC-ORD/gimie> a schema:SoftwareSourceCode ;
    schema:CodeRepository <https://github.com/SDSC-ORD/gimie> ;
    schema:author <https://api.github.com/orgs/SDSC-ORD> ;
    schema:contributor <https://api.github.com/users/cmdoret>,
        <https://api.github.com/users/martinfontanet>,
        <https://api.github.com/users/rmfranken>,
        <https://api.github.com/users/sabinem>,
        <https://api.github.com/users/sabrinaossey> ;
    schema:dateCreated "2022-12-07" ;
    schema:dateModified "2023-01-31" ;
    schema:description "Extract linked metadata from repositories" ;
    schema:downloadUrl <https://api.github.com/repos/SDSC-ORD/gimie/tarball> ;
    schema:keywords "fair-data",
        "git",
        "linked-open-data",
        "metadata-extraction",
        "python",
        "scientific-software" ;
    schema:license <https://spdx.org/licenses/Apache-2.0> ;
    schema:name "SDSC-ORD/gimie" ;
    schema:programmingLanguage "Makefile",
        "Python" ;
    schema:version "v0.2.0" .

<https://api.github.com/orgs/SDSC-ORD> a schema:Organization ;
    schema:description "" ;
    schema:legalName "Swiss Data Science Center - ORD" ;
    schema:logo <https://avatars.githubusercontent.com/u/114115753?v=4> ;
    schema:name "SDSC-ORD" .
```

### CODE REVIEW

**Comment by rmfranken** [comment]
First of all I think this is a great start, this is valid linked data and it works. I validated your extracted instance data example against our shapes graph from the imaging ontology. This produced only 1 error:

sh:result    [ rdf:type                      sh:ValidationResult ;
                 sh:focusNode                  <https://github.com/SDSC-ORD/gimie> ;
                 sh:resultMessage              "Value must have one of the following datatypes: xsd:date, xsd:dateTime" ;
                 sh:resultPath                 schema:dateCreated ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:OrConstraintComponent ;
                 sh:sourceShape                schema:CreativeWork-dateCreated ;
                 sh:value                      "2022-12-07"
               ]

in otherwords: the datecreated must hbe of type xsd:date or xsd:dateTime. I estimate this should be an easy fix. Right now, dateModified is not a property in the ontology, but I expect that if we ever add it, it should also be a xsd:date(Time).

Apart from that: I see nothing wrong with the extraction part of this script, and can only think of improvements on "serializing to LD" part. 

For instance: We are currently not making full use of picklists. (programming language), I would try to make the programming language an object which can have information attached again (relations are always preferred to flat values in my opinion), but since schema.org does not force you to use an object this string is fine for now - it still conforms.

Another thing we have to be careful of is empty values. Right now the schema:description for our organization is "". This means a shacl shape which is checking for the presence of a value for the property "schema:description" is totally okay with this, even though "" is hardly a valid way to fill a property. Of course, writing a better shape constraint like sh:minLength 1 would catch this, but it's bad practice to make instance data contain empty strings. If it's empty, leave it empty: You don't have the data, so don't clog the dataset with emptiness. I can't think of a good reason to keep it in, but am always open for your perspective.

Again: this is a minor thing, the data is valid linked data, and since we are judge, jury and executioner, we can literally decide whether or not we care about it. (We can make the shapes less strict or more strict). But since we are trying to follow schema.org mostly, I think this is good for now .

**Comment by cmdoret** [comment]
Good catch, value types were not enabled in calamus. I fixed that. It looks a bit uglier, but now we have the dates :grin: 

```ttl
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://github.com/SDSC-ORD/gimie> a schema:SoftwareSourceCode ;
    schema:CodeRepository [ ] ;
    schema:author <https://api.github.com/orgs/SDSC-ORD> ;
    schema:contributor <https://api.github.com/users/cmdoret>,
        <https://api.github.com/users/martinfontanet>,
        <https://api.github.com/users/rmfranken>,
        <https://api.github.com/users/sabinem>,
        <https://api.github.com/users/sabrinaossey> ;
    schema:dateCreated "2022-12-07"^^xsd:date ;
    schema:dateModified "2023-01-31"^^xsd:date ;
    schema:description "Extract linked metadata from repositories"^^xsd:string ;
    schema:downloadUrl [ ] ;
    schema:keywords "fair-data"^^xsd:string,
        "git"^^xsd:string,
        "linked-open-data"^^xsd:string,
        "metadata-extraction"^^xsd:string,
        "python"^^xsd:string,
        "scientific-software"^^xsd:string ;
    schema:license [ ] ;
    schema:name "SDSC-ORD/gimie"^^xsd:string ;
    schema:programmingLanguage "Makefile"^^xsd:string,
        "Python"^^xsd:string ;
    schema:version "v0.2.0"^^xsd:string .

<https://api.github.com/orgs/SwissDataScienceCenter> a schema:Organization ;
    schema:description "An ETH Domain initiative for accelerating the adoption of data science" ;
    schema:name "SwissDataScienceCenter" .

<https://api.github.com/orgs/koszullab> a schema:Organization ;
    schema:description "" ;
    schema:name "koszullab" .

<https://api.github.com/users/cmdoret> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD>,
        <https://api.github.com/orgs/SwissDataScienceCenter>,
        <https://api.github.com/orgs/koszullab> ;
    schema:identifier "cmdoret" ;
    schema:name "Cyril Matthey-Doret" .

<https://api.github.com/users/martinfontanet> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD> ;
    schema:identifier "martinfontanet" .

<https://api.github.com/users/rmfranken> a schema:Person ;
    schema:identifier "rmfranken" .

<https://api.github.com/users/sabinem> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD> ;
    schema:identifier "sabinem" ;
    schema:name "Sabine Maennel" .

<https://api.github.com/users/sabrinaossey> a schema:Person ;
    schema:identifier "sabrinaossey" ;
    schema:name "sabrinaossey" .

<https://api.github.com/orgs/SDSC-ORD> a schema:Organization ;
    schema:description "" ;
    schema:legalName "Swiss Data Science Center - ORD" ;
    schema:logo <https://avatars.githubusercontent.com/u/114115753?v=4> ;
    schema:name "SDSC-ORD" .
```

**Comment by rmfranken** [comment]
Beautiful! Only now we have some interesting empty blank nodes. (license, downloadurl, coderepository) Not sure how your change with the datatypes managed to cause that 😕 Since I see you only changed a single line...

**Comment by cmdoret** [comment]
:thinking: weird, i "fixed" it by making them `Raw` fields instead of IRI. Now they appear quoted in the turtle instead of between angle brackets... Does that seem OK to you?

```ttl
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://github.com/SDSC-ORD/gimie> a schema:SoftwareSourceCode ;
    schema:CodeRepository "https://github.com/SDSC-ORD/gimie" ;
    schema:author <https://api.github.com/orgs/SDSC-ORD> ;
    schema:contributor <https://api.github.com/users/cmdoret>,
        <https://api.github.com/users/martinfontanet>,
        <https://api.github.com/users/rmfranken>,
        <https://api.github.com/users/sabinem>,
        <https://api.github.com/users/sabrinaossey> ;
    schema:dateCreated "2022-12-07"^^xsd:date ;
    schema:dateModified "2023-01-31"^^xsd:date ;
    schema:description "Extract linked metadata from repositories"^^xsd:string ;
    schema:downloadUrl "https://api.github.com/repos/SDSC-ORD/gimie/tarball" ;
    schema:keywords "fair-data"^^xsd:string,
        "git"^^xsd:string,
        "linked-open-data"^^xsd:string,
        "metadata-extraction"^^xsd:string,
        "python"^^xsd:string,
        "scientific-software"^^xsd:string ;
    schema:license "https://spdx.org/licenses/Apache-2.0" ;
    schema:name "SDSC-ORD/gimie"^^xsd:string ;
    schema:programmingLanguage "Makefile"^^xsd:string,
        "Python"^^xsd:string ;
    schema:version "v0.2.0"^^xsd:string .

<https://api.github.com/orgs/SwissDataScienceCenter> a schema:Organization ;
    schema:description "An ETH Domain initiative for accelerating the adoption of data science" ;
    schema:name "SwissDataScienceCenter" .

<https://api.github.com/orgs/koszullab> a schema:Organization ;
    schema:description "" ;
    schema:name "koszullab" .

<https://api.github.com/users/cmdoret> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD>,
        <https://api.github.com/orgs/SwissDataScienceCenter>,
        <https://api.github.com/orgs/koszullab> ;
    schema:identifier "cmdoret" ;
    schema:name "Cyril Matthey-Doret" .

<https://api.github.com/users/martinfontanet> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD> ;
    schema:identifier "martinfontanet" .

<https://api.github.com/users/rmfranken> a schema:Person ;
    schema:identifier "rmfranken" .

<https://api.github.com/users/sabinem> a schema:Person ;
    schema:affiliation <https://api.github.com/orgs/SDSC-ORD> ;
    schema:identifier "sabinem" ;
    schema:name "Sabine Maennel" .

<https://api.github.com/users/sabrinaossey> a schema:Person ;
    schema:identifier "sabrinaossey" ;
    schema:name "sabrinaossey" .

<https://api.github.com/orgs/SDSC-ORD> a schema:Organization ;
    schema:description "" ;
    schema:legalName "Swiss Data Science Center - ORD" ;
    schema:logo <https://avatars.githubusercontent.com/u/114115753?v=4> ;
    schema:name "SDSC-ORD" .
```

**Comment by rmfranken** [comment]
Hmmm, maybe we are looking for fields.IRIReference? Let's give it a short look tomorrow because being able to refer to IRI's is pretty important. I could think of a way around it by using rdfLib to turn that string into an rdfLib term and representing it as a URIRef, but that seems like hitting a nail with the back of a drill rather than a hammer.

**Comment by cmdoret** [comment]
IRI serialization had some issues in calamus, I proposed changes upstream in
https://github.com/SwissDataScienceCenter/calamus/pull/83 which should fix our issue here.

**Comment by cmdoret** [comment]
As a temporary solution, I redefined `IRI` in gimie.models. When calamus will have implemented the fix and made a new release, we drop it.

**Review by rmfranken — APPROVED** [review]
Looks good, temp fix for IRI typing seems to be working :)

**Pull request merged**
